import { NextResponse } from 'next/server'

interface Player {
  Flexibility: number
  Speed: number
  Aim: number
  ACC: number
  ADP: number
  PS: number
  Overall: number
  nationality: string | null
  sector: string | null
  playstyle: string | null
  alignment: string | null
}

// Dados dos jogadores (substitua pelos seus dados reais)
const playerData: Record<string, Player> = {
  Suka: {
    Flexibility: 88,
    Speed: 91,
    Aim: 90,
    ACC: 88,
    ADP: 86,
    PS: 88,
    Overall: 88,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Miro: {
    Flexibility: 90,
    Speed: 89,
    Aim: 85,
    ACC: 89,
    ADP: 87,
    PS: 87,
    Overall: 87,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Rian: {
    Flexibility: 75,
    Speed: 86,
    Aim: 73,
    ACC: 75,
    ADP: 78,
    PS: 79,
    Overall: 77,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Rion: {
    Flexibility: 82,
    Speed: 90,
    Aim: 80,
    ACC: 84,
    ADP: 88,
    PS: 90,
    Overall: 85,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Yumi: {
    Flexibility: 95,
    Speed: 88,
    Aim: 98,
    ACC: 98,
    ADP: 95,
    PS: 97,
    Overall: 95,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  A2: {
    Flexibility: 97,
    Speed: 86,
    Aim: 98,
    ACC: 99,
    ADP: 99,
    PS: 98,
    Overall: 96,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Alfa: {
    Flexibility: 85,
    Speed: 98,
    Aim: 91,
    ACC: 96,
    ADP: 85,
    PS: 95,
    Overall: 92,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Seised: {
    Flexibility: 86,
    Speed: 97,
    Aim: 95,
    ACC: 92,
    ADP: 85,
    PS: 94,
    Overall: 91,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Zender: {
    Flexibility: 85,
    Speed: 90,
    Aim: 90,
    ACC: 88,
    ADP: 88,
    PS: 95,
    Overall: 89,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Tadex: {
    Flexibility: 97,
    Speed: 94,
    Aim: 95,
    ACC: 88,
    ADP: 96,
    PS: 96,
    Overall: 94,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Adrian: {
    Flexibility: 90,
    Speed: 88,
    Aim: 99,
    ACC: 95,
    ADP: 90,
    PS: 85,
    Overall: 91,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Hespera: {
    Flexibility: 90,
    Speed: 99,
    Aim: 95,
    ACC: 93,
    ADP: 90,
    PS: 98,
    Overall: 94,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Hedinn: {
    Flexibility: 92,
    Speed: 99, // assuming this is 94 based on context
    Aim: 79,
    ACC: 78,
    ADP: 80,
    PS: 74, // assuming this is correct
    Overall: 84,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Plep: {
    Flexibility: 93,
    Speed: 94,
    Aim: 84,
    ACC: 83,
    ADP: 82,
    PS: 92,
    Overall: 88,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Annis: {
    Flexibility: 71,
    Speed: 72,
    Aim: 82,
    ACC: 80,
    ADP: 73,
    PS: 80,
    Overall: 75,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Pivo: {
    Flexibility: 73,
    Speed: 75,
    Aim: 73,
    ACC: 76,
    ADP: 77,
    PS: 73,
    Overall: 74,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Terami: {
    Flexibility: 75,
    Speed: 80,
    Aim: 75,
    ACC: 76,
    ADP: 71,
    PS: 80,
    Overall: 76,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Ren: {
    Flexibility: 79,
    Speed: 92,
    Aim: 78,
    ACC: 79,
    ADP: 80,
    PS: 94,
    Overall: 83,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Over1kBlades: {
    Flexibility: 77,
    Speed: 79,
    Aim: 78,
    ACC: 79,
    ADP: 76,
    PS: 77,
    Overall: 77,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Renterik: {
    Flexibility: 75,
    Speed: 76,
    Aim: 73,
    ACC: 70,
    ADP: 69,
    PS: 71,
    Overall: 72,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Lunicia: {
    Flexibility: 78,
    Speed: 79,
    Aim: 76,
    ACC: 77,
    ADP: 76,
    PS: 73,
    Overall: 76,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Jenox: {
    Flexibility: 82,
    Speed: 81,
    Aim: 86,
    ACC: 83,
    ADP: 80,
    PS: 79,
    Overall: 82,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Zangetsu: {
    Flexibility: 88,
    Speed: 86,
    Aim: 94,
    ACC: 88,
    ADP: 89,
    PS: 88,
    Overall: 89,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Jade: {
    Flexibility: 81,
    Speed: 80,
    Aim: 89,
    ACC: 88,
    ADP: 86,
    PS: 79,
    Overall: 83,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Aliya: {
    Flexibility: 81,
    Speed: 79,
    Aim: 80,
    ACC: 75,
    ADP: 75,
    PS: 73,
    Overall: 77,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Thyme: {
    Flexibility: 77,
    Speed: 88,
    Aim: 79,
    ACC: 77,
    ADP: 75,
    PS: 70,
    Overall: 78,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Lunnarii: {
    Flexibility: 85,
    Speed: 79,
    Aim: 81,
    ACC: 80,
    ADP: 79,
    PS: 77,
    Overall: 79,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Paladino: {
    Flexibility: 80,
    Speed: 84,
    Aim: 83,
    ACC: 82,
    ADP: 75,
    PS: 85,
    Overall: 81,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
  Syal: {
    Flexibility: 85,
    Speed: 85,
    Aim: 85,
    ACC: 82,
    ADP: 90,
    PS: 80,
    Overall: 84,
    nationality: null,
    sector: null,
    playstyle: null,
    alignment: null,
  },
}

export async function GET() {
  return NextResponse.json(playerData)
}
