import { NextResponse } from 'next/server'

interface Player {
  id: string
  name: string
  guild: string | null
  nationality: string | null
  sector: string | null
  playstyle: string
  alignment: string | null
  Flexibility: number
  Speed: number
  Aim: number
  ACC: number
  ADP: number
  PS: number
  overall: number
  OBS?: string
}

const playerData: Player[] = [
  {
    id: '1',
    name: 'Suka',
    guild: 'Moonshine',
    nationality: 'Russia',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 88,
    Speed: 91,
    Aim: 90,
    ACC: 88,
    ADP: 86,
    PS: 88,
    overall: 88,
  },
  {
    id: '2',
    name: 'Miro',
    guild: 'Moonshine',
    nationality: 'Russia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 84,
    Speed: 85,
    Aim: 82,
    ACC: 81,
    ADP: 79,
    PS: 81,
    overall: 82,
  },
  {
    id: '3',
    name: 'Rian',
    guild: 'unemployed',
    nationality: 'Colombia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 75,
    Speed: 86,
    Aim: 73,
    ACC: 75,
    ADP: 78,
    PS: 79,
    overall: 77,
  },
  {
    id: '4',
    name: 'Rion',
    guild: 'Nightfall',
    nationality: 'Canada',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 82,
    Speed: 90,
    Aim: 80,
    ACC: 84,
    ADP: 88,
    PS: 90,
    overall: 85,
  },
  {
    id: '5',
    name: 'Yumi',
    guild: 'Nightfall',
    nationality: 'France',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 95,
    Speed: 88,
    Aim: 98,
    ACC: 98,
    ADP: 95,
    PS: 97,
    overall: 95,
  },
  {
    id: '6',
    name: 'A2',
    guild: 'LS',
    nationality: 'Palestine',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 97,
    Speed: 86,
    Aim: 98,
    ACC: 99,
    ADP: 99,
    PS: 98,
    overall: 96,
  },
  {
    id: '7',
    name: 'Alfa',
    guild: 'LS',
    nationality: 'Brazil',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 85,
    Speed: 98,
    Aim: 91,
    ACC: 96,
    ADP: 85,
    PS: 95,
    overall: 92,
  },
  {
    id: '8',
    name: 'Seised',
    guild: 'LS',
    nationality: 'Mexico',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 86,
    Speed: 97,
    Aim: 95,
    ACC: 92,
    ADP: 85,
    PS: 94,
    overall: 91,
  },
  {
    id: '9',
    name: 'Zender (Sender)',
    guild: 'Nightfall',
    nationality: 'Russia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 85,
    Speed: 90,
    Aim: 90,
    ACC: 88,
    ADP: 88,
    PS: 95,
    overall: 89,
  },
  {
    id: '10',
    name: 'Tadex',
    guild: 'LS',
    nationality: 'Slovenia',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 97,
    Speed: 94,
    Aim: 95,
    ACC: 88,
    ADP: 96,
    PS: 96,
    overall: 94,
  },
  {
    id: '11',
    name: 'Adrian',
    guild: 'Nightfall',
    nationality: 'Romania',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 90,
    Speed: 88,
    Aim: 99,
    ACC: 95,
    ADP: 90,
    PS: 85,
    overall: 91,
  },
  {
    id: '12',
    name: 'Hespera',
    guild: 'LS',
    nationality: 'USA',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 90,
    Speed: 99,
    Aim: 95,
    ACC: 93,
    ADP: 90,
    PS: 98,
    overall: 94,
  },
  {
    id: '13',
    name: 'Hedinn',
    guild: 'LS',
    nationality: 'Turkey',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 92,
    Speed: 99,
    Aim: 79,
    ACC: 78,
    ADP: 80,
    PS: 74,
    overall: 84,
    OBS: "Didn't Play Enough to be 100% sure.",
  },
  {
    id: '14',
    name: 'Plep',
    guild: 'LS',
    nationality: 'Philipines',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 93,
    Speed: 94,
    Aim: 84,
    ACC: 83,
    ADP: 82,
    PS: 92,
    overall: 88,
    OBS: "Didn't Play Enough to be 100% sure.",
  },
  {
    id: '15',
    name: 'Annis',
    guild: 'LS',
    nationality: 'Poland',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 76,
    Speed: 80,
    Aim: 82,
    ACC: 80,
    ADP: 73,
    PS: 80,
    overall: 78,
  },
  {
    id: '16',
    name: 'Pivo',
    guild: 'Moonshine',
    nationality: 'Russia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 73,
    Speed: 75,
    Aim: 73,
    ACC: 76,
    ADP: 77,
    PS: 73,
    overall: 74,
  },
  {
    id: '17',
    name: 'Terami',
    guild: 'Atomix',
    nationality: 'Ukraine',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 75,
    Speed: 80,
    Aim: 75,
    ACC: 76,
    ADP: 71,
    PS: 80,
    overall: 76,
  },
  {
    id: '18',
    name: 'Ren',
    guild: 'unemployed',
    nationality: 'Argentina',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 79,
    Speed: 92,
    Aim: 78,
    ACC: 79,
    ADP: 80,
    PS: 94,
    overall: 83,
  },
  {
    id: '19',
    name: 'Over1kBlades',
    guild: 'unemployed',
    nationality: 'Russia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 77,
    Speed: 79,
    Aim: 78,
    ACC: 79,
    ADP: 76,
    PS: 77,
    overall: 77,
  },
  {
    id: '20',
    name: 'Renterik',
    guild: 'Moonshine',
    nationality: 'Russia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 75,
    Speed: 76,
    Aim: 73,
    ACC: 70,
    ADP: 69,
    PS: 71,
    overall: 72,
  },
  {
    id: '21',
    name: 'Lunicia',
    guild: 'Nightfall',
    nationality: 'USA',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 78,
    Speed: 79,
    Aim: 76,
    ACC: 77,
    ADP: 76,
    PS: 73,
    overall: 76,
  },
  {
    id: '22',
    name: 'Jenox',
    guild: 'Nightfall',
    nationality: 'Argentina',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 82,
    Speed: 81,
    Aim: 86,
    ACC: 83,
    ADP: 80,
    PS: 79,
    overall: 82,
  },
  {
    id: '23',
    name: 'Zangetsu',
    guild: 'unemployed',
    nationality: 'Italy',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 88,
    Speed: 86,
    Aim: 94,
    ACC: 88,
    ADP: 89,
    PS: 88,
    overall: 89,
  },
  {
    id: '24',
    name: 'Jade',
    guild: 'unemployed',
    nationality: 'France',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 81,
    Speed: 80,
    Aim: 89,
    ACC: 88,
    ADP: 86,
    PS: 79,
    overall: 83,
  },
  {
    id: '25',
    name: 'Aliya',
    guild: 'LS',
    nationality: 'USA',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 81,
    Speed: 79,
    Aim: 80,
    ACC: 75,
    ADP: 75,
    PS: 73,
    overall: 77,
  },
  {
    id: '26',
    name: 'Thyme',
    guild: 'unemployed',
    nationality: 'Canada',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 77,
    Speed: 88,
    Aim: 79,
    ACC: 77,
    ADP: 75,
    PS: 70,
    overall: 78,
  },
  {
    id: '27',
    name: 'Lunnarii',
    guild: 'Nightfall',
    nationality: 'USA',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 85,
    Speed: 79,
    Aim: 81,
    ACC: 80,
    ADP: 79,
    PS: 77,
    overall: 79,
  },
  {
    id: '28',
    name: 'Paladino',
    guild: 'Nightfall',
    nationality: 'Brazil',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 80,
    Speed: 84,
    Aim: 83,
    ACC: 82,
    ADP: 75,
    PS: 85,
    overall: 81,
  },
  {
    id: '29',
    name: 'Syal',
    guild: 'unemployed',
    nationality: 'Ukraine',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 85,
    Speed: 85,
    Aim: 85,
    ACC: 82,
    ADP: 90,
    PS: 80,
    overall: 84,
  },
  {
    id: '30',
    name: 'Reanu Keeves',
    guild: 'LS',
    nationality: 'Germany',
    sector: null,
    playstyle: '',
    alignment: null,
    Flexibility: 75,
    Speed: 80,
    Aim: 80,
    ACC: 72,
    ADP: 67,
    PS: 68,
    overall: 73,
  },
  {
    id: '31',
    name: 'Asura',
    guild: 'Nightfall',
    nationality: 'USA',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 84,
    Speed: 95,
    Aim: 90,
    ACC: 91,
    ADP: 87,
    PS: 86,
    overall: 89,
  },
  {
    id: '32',
    name: 'Leach',
    guild: 'Nightfall',
    nationality: 'USA',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 80,
    Speed: 78,
    Aim: 81,
    ACC: 82,
    ADP: 76,
    PS: 79,
    overall: 79,
  },
  {
    id: '33',
    name: 'Ryd',
    guild: 'Nightfall',
    nationality: 'Italy',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 79,
    Speed: 81,
    Aim: 85,
    ACC: 90,
    ADP: 77,
    PS: 80,
    overall: 81,
  },
  {
    id: '34',
    name: 'Esdeath',
    guild: 'Nightfall',
    nationality: 'Philipines',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 82,
    Speed: 80,
    Aim: 85,
    ACC: 82,
    ADP: 78,
    PS: 84,
    overall: 82,
  },
  {
    id: '35',
    name: 'Cat',
    guild: 'Nightfall',
    nationality: 'USA',
    sector: null,
    playstyle: '',
    alignment: null,
    Flexibility: 70,
    Speed: 69,
    Aim: 68,
    ACC: 74,
    ADP: 68,
    PS: 69,
    overall: 68,
  },
  {
    id: '36',
    name: 'BRuki',
    guild: 'LS',
    nationality: 'Italy',
    sector: null,
    playstyle: 'AGGRO',
    alignment: null,
    Flexibility: 78,
    Speed: 80,
    Aim: 78,
    ACC: 76,
    ADP: 70,
    PS: 75,
    overall: 76,
  },
  {
    id: '37',
    name: 'Acros',
    guild: 'LS',
    nationality: 'USA',
    sector: null,
    playstyle: '',
    alignment: null,
    Flexibility: 78,
    Speed: 81,
    Aim: 83,
    ACC: 75,
    ADP: 70,
    PS: 73,
    overall: 76,
  },
  {
    id: '38',
    name: 'Yoda',
    guild: 'unemployed',
    nationality: 'Dominican',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 68,
    Speed: 70,
    Aim: 69,
    ACC: 70,
    ADP: 65,
    PS: 71,
    overall: 68,
  },
  {
    id: '39',
    name: 'Sushi',
    guild: 'unemployed',
    nationality: 'Serbia',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 65,
    Speed: 62,
    Aim: 65,
    ACC: 68,
    ADP: 66,
    PS: 65,
    overall: 65,
  },
  {
    id: '40',
    name: 'Blitz Comet',
    guild: 'unemployed',
    nationality: 'Georgia',
    sector: null,
    playstyle: 'MIX',
    alignment: null,
    Flexibility: 80,
    Speed: 88,
    Aim: 85,
    ACC: 80,
    ADP: 75,
    PS: 82,
    overall: 81,
  },
  {
    id: '41',
    name: 'Sirzechs',
    guild: 'Atomix',
    nationality: 'Brazil',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 75,
    Speed: 78,
    Aim: 77,
    ACC: 72,
    ADP: 70,
    PS: 72,
    overall: 73,
  },
  {
    id: '42',
    name: 'Kuze',
    guild: 'unemployed',
    nationality: 'Argentina',
    sector: null,
    playstyle: 'PAS',
    alignment: null,
    Flexibility: 78,
    Speed: 78,
    Aim: 80,
    ACC: 83,
    ADP: 84,
    PS: 82,
    overall: 80,
  },
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const id = searchParams.get('id')

  if (id) {
    const player = playerData.find((p) => p.id === id)
    if (player) {
      return NextResponse.json(player)
    } else {
      return NextResponse.json({ message: 'Player not found' }, { status: 404 })
    }
  }

  return NextResponse.json(playerData)
}
